feature/cluster_rollingupgrade_when_certificate_renewal: init
PLsergent/nifikop pull request #1
Opened 2022-05-18 15:37 UTC by PLsergent

| Q               | A
| --------------- | ---
| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | Apache 2.0

### What's in this PR?

### Why?

### Additional context

### Checklist

- [ ] Implementation tested
- [ ] Error handling code meets the [guideline](docs/error-handling-guide.md)
- [ ] Logging code meets the guideline
- [ ] User guide and development docs updated (if needed)
- [ ] Append changelog with changes

### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

2022-05-19 07:40 UTC, juldrixx requested changes

2022-05-19 07:40 UTC, juldrixx commented on api/v1alpha1/nificluster_types.go
> +	ClusterRevision int `json:"revision,omitempty"`
```suggestion
	CertificateRevision int `json:"certificateRevision,omitempty"`
```

2022-05-19 07:40 UTC, juldrixx commented on controllers/nificluster_controller.go
> +		// PL
```suggestion
```

2022-05-19 07:40 UTC, juldrixx commented on controllers/nificluster_controller.go
> +	// pass a certificate instead of instance PL
```suggestion
```

2022-05-19 07:40 UTC, juldrixx commented on pkg/pki/certmanagerpki/certmanager_pki.go
> +	// Logic get certmanager info PL
```suggestion
```

2022-05-19 07:40 UTC, juldrixx commented on pkg/pki/certmanagerpki/certmanager_pki.go
> +			// HERE PL
```suggestion
```

2022-05-19 07:41 UTC, juldrixx commented
Et au passage, la PR c'est pas sur ton projet à toi qu'il fallait la faire mais sur le projet source 😆

2022-05-19 07:44 UTC, juldrixx commented
Pour le status sur la révision, selon moi il faut le mettre à jour à 2 moments. Le première fois quand la valeur n'est pas mise. Et une deuxième fois quand le rollingUpgrade est terminé.

2022-05-23 09:01 UTC, PLsergent commented
Oui je voulais d'abord faire une PR sur mon projet avant de la faire du le vrai repo 🤒

2022-08-24 15:21 UTC, closed without merging